version: "3"
services:
  react-app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: milan-react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./src:/app/src
      - ./app/node_modules

  api-server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: milan-api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server:/app
      - ./app/node_modules

networks:
  mern-app:
    driver: bridge
